#!/usr/bin/env python3
"""
Hermes HOWL Nightly Review - Runs daily at 23:55
Full self-improvement analysis across 10 pillars.
"""
import json
import os
import sys
from pathlib import Path
from datetime import datetime, timedelta

# Add project root to path
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

def git_pull():
    """Pull latest changes from repo"""
    os.system("git pull > /dev/null 2>&1")

def load_json(filepath, default=None):
    """Load JSON file with fallback"""
    try:
        with open(filepath, 'r') as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return default if default is not None else {}

def save_json(filepath, data):
    """Save JSON file"""
    with open(filepath, 'w') as f:
        json.dump(data, f, indent=2)

def append_to_memory(content):
    """Append to memory/MEMORY.md"""
    memory_file = PROJECT_ROOT / "memory" / "MEMORY.md"
    with open(memory_file, 'a') as f:
        f.write(content + "\n")

def main():
    print(f"[HOWL Review] Starting at {datetime.utcnow().isoformat()}Z")
    
    # Step 1: Git pull
    git_pull()
    
    # Step 2: Gather data for analysis
    # In a real implementation, we would analyze:
    # - Core metrics (trades, win rate, PF, avg win/loss)
    # - Scanner source breakdown
    # - Monster trade dependency
    # - Fee Drag Ratio
    # - etc.
    
    # For now, we'll create a placeholder analysis
    today = datetime.utcnow().date()
    yesterday = today - timedelta(days=1)
    
    howl_content = f"""
# HOWL Review - {today.isoformat()}

## Executive Summary
- Placeholder HOWL analysis executed at {datetime.utcnow().isoformat()}Z
- Real implementation would analyze performance across 10 pillars

## Core Metrics (Placeholder)
- Total trades: 0
- Win rate: 0%
- Profit factor: 0.0
- Average win: $0
- Average loss: $0

## Scanner Performance (Placeholder)
- ORCA: 0 trades
- KOMODO: 0 trades
- SHARK: 0 trades
- SENTINEL: 0 trades
- CONDOR: 0 trades
- RHINO: 0 trades
- BARRACUDA: 0 trades
- BISON: 0 trades

## Risk Management
- Current regime: {load_json(PROJECT_ROOT / 'config' / 'risk-regime.json', {}).get('riskMode', 'UNKNOWN')}
- Max positions: 3 (hard constraint)
- Leverage band: 7-10x (hard constraint)

## Action Items (Risk-Reducing Only)
- No risk-increasing changes applied automatically
- All config changes require human approval if they increase risk

---
*Generated by Hermes HOWL Review System*
"""
    
    # Step 3: Write nightly report
    howl_file = PROJECT_ROOT / "memory" / f"howl-{today.isoformat()}.md"
    with open(howl_file, 'w') as f:
        f.write(howl_content)
    
    # Step 4: Append to MEMORY.md (distilled summary)
    distilled_summary = f"[{today.isoformat()}] HOWL completed. Placeholder analysis. No risk-increasing changes applied."
    append_to_memory(distilled_summary)
    
    # Step 5: Git commit and push
    os.system(f"git add memory/howl-{today.isoformat()}.md memory/MEMORY.md > /dev/null 2>&1")
    os.system(f'git commit -m "HOWL: nightly review for {today.isoformat()}" > /dev/null 2>&1')
    os.system("git push > /dev/null 2>&1")
    
    print(f"[HOWL Review] Completed for {today.isoformat()}")

if __name__ == "__main__":
    main()